service:
  listen_address: :7072
  db_file: ./chickenlittle.db
integrations:
  hipchat:
    hipchat_auth_token: NotYetImplemented
    hipchat_announce_room:  NotYetImplemented
  victorops:
    api_key:  your-api-key-goes-here
