people:
- user: joe
  victorops_routing_key: joeuser
  full_name: Joe User
- user: sam
  victorops_routing_key: samadmin
  full_name: Sam Admin
service:
  listen_address: :7072
integrations:
  hipchat:
    hipchat_auth_token: NotYetImplemented
    hipchat_announce_room:  NotYetImplemented
  victorops:
    api_key:  your-api-key-goes-here
